export const hololiveTalents=[
  {id:'0', gen:'Gen 0',name:'Tokino Soda'},
  {id:'1', gen:'Gen 0',name:'Robocosan'},
  {id:'2', gen:'Gen 0',name:'AZKi'},
  {id:'3', gen:'Gen 0',name:'Sakura Miko'},
  {id:'4', gen:'Gen 0',name:'Hoshimachi Suisei'},
  {id:'5', gen:'Gen 1',name:'Yozora Mel'},
  {id:'6', gen:'Gen 1',name:'Aki Rosenthal'},
  {id:'7', gen:'Gen 1',name:'Akai Haato'},
  {id:'9', gen:'Gen 1',name:'Shirakami Fubuki'},
  {id:'10', gen:'Gen 1',name:'Natsuiro Matsuri'},
  {id:'11', gen:'Gen 2',name:'Minato Aqua'},
  {id:'12', gen:'Gen 2',name:'Murasaki Shion'},
  {id:'13', gen:'Gen 2',name:'Nakiri Ayame'},
  {id:'14', gen:'Gen 2',name:'Yuzuki Choco'},
  {id:'15', gen:'Gen 2',name:'Oozora Subaru'},
  {id:'16', gen:'Gamers',name:'Shirakami Fubuki'},
  {id:'17', gen:'Gamers',name:'Ookami Mio'},
  {id:'18', gen:'Gamers',name:'Nekomata Okayu'},
  {id:'19', gen:'Gamers',name:'Inugami Korone'},
  {id:'20', gen:'Gen 3',name:'Usada Pecola'},
  {id:'21', gen:'Gen 3',name:'Shiranui Flare'},
  {id:'22', gen:'Gen 3',name:'Shirogane Noel'},
  {id:'23', gen:'Gen 3',name:'Houshou Marine'},
  {id:'22', gen:'Gen 4',name:'Amane Kanata'},
  {id:'23', gen:'Gen 4',name:'Tsunomaki Watame'},
  {id:'24', gen:'Gen 4',name:'Tokoyami Towa'},
  {id:'25', gen:'Gen 4',name:'Himenori Luna'},
  {id:'26', gen:'Gen 5',name:'Yukihana Lamy'},
  {id:'27', gen:'Gen 5',name:'Momosuzu Nene'},
  {id:'28', gen:'Gen 5',name:'Shishiro Botan'},
  {id:'29', gen:'Gen 5',name:'Omaru Polka'}]
  